[package]
name = "indigo_uploader"
version = "0.1.1"
authors = [ "Savelev_Aleksandr@epam.com" ]

[dependencies]
rustc-serialize = "0.3.16"
postgres-binary-copy = "0.1.1"
flate2 = "0.2.9"
regex = "*"
time = "*"
threadpool = "0.2"
num_cpus = "0.2"
getopts = "0.2"
yaml-rust = "0.3.0"

[dependencies.postgres]
version = "0.10"
features = ["rustc-serialize"]

[lib]
name = "sd_import"
path = "src/sd_import/sd_import.rs"

[[bin]]
name = "indigo_uploader"