language: python
dist: trusty
sudo: required
os:
  - linux
before_script:
  - sudo apt-get update -qq && sudo apt-get install -y libfreetype6-dev libfontconfig1-dev
script:
  - python build_scripts/indigo-release-libs.py