env:
  build: ./
  dockerfile: ./Dockerfile
  volumes:
    - ./:/code
  tty: false
  # Command contains workaround to set permissions for local user
  command: 
    # bash -c "useradd -m -s /bin/bash $USER || true && /bin/su -s /bin/bash -c 'npm install && npm run gulp archive' $USER"
    bash -c "npm install && npm run gulp archive"